[profile.default]
via_ir = true
src = "src"
test = "test"
out = "out"
optimizer = true
optimizer_runs = 200
evm_version = "cancun"
solc_version = "0.8.30"

remappings = [
  "forge-std/=lib/forge-std/src/",
  "openzeppelin-contracts/=lib/openzeppelin-contracts/"
]

[invariant]
runs = 32
depth = 64
call_override = false
fail_on_revert = false
