[profile.default]
via_ir = true
src = "src"
test = "test"
out = "out"
optimizer = true
optimizer_runs = 200
evm_version = "cancun"
allow_paths = ["../lib"]

remappings = [
  "lib/=../lib/",
  "openzeppelin-contracts/=../lib/openzeppelin-contracts/",
  "forge-std/=../lib/forge-std/src/"
]

[invariant]
runs = 32
depth = 64
call_override = false
fail_on_revert = false
